/**
 * Report rendering.
 *
 * Reports are rendered to a plain-text/Markdown document and written under
 * REPORT_ROOT by the report service. The renderer itself is pure so it can be
 * unit-tested and reused by an export worker on another machine.
 */

export interface ReportPlayer {
  firstName: string;
  lastName: string;
  position: string;
  nationality?: string | null;
  teamName?: string | null;
}

export interface ReportMetrics {
  season: string;
  matches: number;
  minutesPlayed: number;
  goalsPer90: number;
  assistsPer90: number;
  xgPer90: number;
  xaPer90: number;
  passAccuracy: number;
  progPassPer90: number;
  duelWinRate: number;
  scoutScore: number;
}

export interface ReportInput {
  title: string;
  summary: string;
  rating: number;
  author?: string | null;
  generatedAt: Date;
  player: ReportPlayer;
  metrics?: ReportMetrics | null;
  /** Absolute public URL of this deployment, from PUBLIC_BASE_URL. */
  baseUrl: string;
  reportId: string;
}

const percent = (value: number): string => `${(value * 100).toFixed(1)}%`;

/**
 * Build the storage key for a report: `<season>/<playerId>/<reportId>.md`.
 * Always relative - the report root may be any mount on any host.
 */
export function reportKey(season: string, playerId: string, reportId: string): string {
  const safeSeason = season.replace(/[^\w.-]/g, '_');
  return `${safeSeason}/${playerId}/${reportId}.md`;
}

export function renderReport(input: ReportInput): string {
  const { player, metrics } = input;
  const name = `${player.firstName} ${player.lastName}`.trim();

  const lines: string[] = [
    `# ${input.title}`,
    '',
    `**Player:** ${name}  `,
    `**Position:** ${player.position}  `,
    `**Team:** ${player.teamName ?? 'Unattached'}  `,
    `**Nationality:** ${player.nationality ?? 'Unknown'}  `,
    `**Rating:** ${input.rating}/10  `,
    `**Author:** ${input.author ?? 'ScoutIQ'}  `,
    `**Generated:** ${input.generatedAt.toISOString()}`,
    '',
    '## Summary',
    '',
    input.summary.trim(),
    '',
  ];

  if (metrics) {
    lines.push(
      `## Season ${metrics.season}`,
      '',
      '| Metric | Value |',
      '| --- | --- |',
      `| Matches | ${metrics.matches} |`,
      `| Minutes | ${metrics.minutesPlayed} |`,
      `| Goals /90 | ${metrics.goalsPer90.toFixed(2)} |`,
      `| Assists /90 | ${metrics.assistsPer90.toFixed(2)} |`,
      `| xG /90 | ${metrics.xgPer90.toFixed(2)} |`,
      `| xA /90 | ${metrics.xaPer90.toFixed(2)} |`,
      `| Progressive passes /90 | ${metrics.progPassPer90.toFixed(2)} |`,
      `| Pass accuracy | ${percent(metrics.passAccuracy)} |`,
      `| Duel win rate | ${percent(metrics.duelWinRate)} |`,
      `| **ScoutIQ score** | **${metrics.scoutScore.toFixed(1)}/100** |`,
      '',
    );
  } else {
    lines.push('## Metrics', '', '_No analytics available for this player yet._', '');
  }

  lines.push('---', '', `Generated by ScoutIQ - ${input.baseUrl}/reports/${input.reportId}`, '');

  return lines.join('\n');
}
