import { CoordinateSystem, ProviderKind } from '@prisma/client';
import { PITCH_LENGTH_M, PITCH_WIDTH_M } from '@/analytics/coordinates';
import {
  BaseProvider,
  type MatchQuery,
  type ProviderCapabilities,
  type ProviderCompetition,
  type ProviderEvent,
  type ProviderLicence,
  type ProviderLineup,
  type ProviderMatch,
  type ProviderPlayer,
  type ProviderSeason,
  type ProviderTeam,
} from '@/providers/types';

/**
 * Demo data provider (§73).
 *
 * ScoutIQ must be fully usable straight after `docker compose up`, with no API
 * keys and no internet access. This provider fabricates a small but complete
 * league: teams, squads, matches, and enough events to drive metrics, DNA,
 * roles, similarity, heatmaps, shot maps and PDF reports.
 *
 * Everything it produces is labelled DEMO DATA in the database and in the UI.
 * It is invented, not observed, and must never be mistaken for real football.
 */

const DEMO_LABEL = 'DEMO DATA';

/**
 * Deterministic PRNG (mulberry32): the same seed produces the same league on
 * every machine, which makes demo output comparable across installations and
 * usable in tests.
 */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

interface DemoSquadPlayer {
  externalId: string;
  firstName: string;
  lastName: string;
  position: string;
  teamExternalId: string;
  /** 0-1 quality knob that shapes the generated events. */
  quality: number;
}

const TEAM_NAMES = [
  'Noordwijk United',
  'Rivierstad FC',
  'Bergveld Athletic',
  'Kustlijn Rovers',
  'Hoogland City',
  'Zandpoort FC',
];

const FIRST_NAMES = [
  'Sem', 'Luuk', 'Daan', 'Bram', 'Finn', 'Noah', 'Milan', 'Jesse', 'Ruben', 'Thijs',
  'Lars', 'Sven', 'Koen', 'Teun', 'Joep', 'Stijn', 'Gijs', 'Mees', 'Cas', 'Tim',
];

const LAST_NAMES = [
  'de Vries', 'Jansen', 'Bakker', 'Visser', 'Smit', 'Meijer', 'Mulder', 'de Boer',
  'Bos', 'Vos', 'Peters', 'Hendriks', 'van Dijk', 'van Leeuwen', 'Dekker', 'Verhoeven',
  'Willems', 'Brouwer', 'Kuiper', 'Timmermans',
];

const FORMATION: { position: string; count: number }[] = [
  { position: 'GK', count: 1 },
  { position: 'CB', count: 2 },
  { position: 'LB', count: 1 },
  { position: 'RB', count: 1 },
  { position: 'CDM', count: 1 },
  { position: 'CM', count: 2 },
  { position: 'LW', count: 1 },
  { position: 'RW', count: 1 },
  { position: 'ST', count: 1 },
];

const SEASON = '2025/2026';

export class DemoProvider extends BaseProvider {
  readonly key = 'scoutiq-demo';
  readonly name = 'ScoutIQ Demo Data';
  readonly kind = ProviderKind.DEMO;
  readonly version = 'demo-v1';
  readonly coordinateSystem = CoordinateSystem.CANONICAL_105_68;

  readonly licence: ProviderLicence = {
    name: 'Fabricated demo content',
    notes:
      'Synthetic data generated by ScoutIQ for demonstration. It describes no ' +
      'real player, team or match, and must never be presented as observed data.',
    commercialUseAllowed: true,
    redistributionAllowed: true,
    attributionRequired: false,
  };

  readonly capabilities: ProviderCapabilities = {
    competitions: true,
    seasons: true,
    teams: true,
    players: true,
    matches: true,
    events: true,
    lineups: true,
    playerStats: false,
    teamStats: false,
    tracking: false,
  };

  private squadCache: DemoSquadPlayer[] | null = null;

  constructor(private readonly matchCount = 30) {
    super();
  }

  override async getCompetitions(): Promise<ProviderCompetition[]> {
    return [
      {
        externalId: 'demo-league',
        name: `Demo Eredivisie (${DEMO_LABEL})`,
        country: 'Netherlands',
        tier: 1,
        type: 'LEAGUE',
        gender: 'MALE',
      },
    ];
  }

  override async getSeasons(): Promise<ProviderSeason[]> {
    return [
      {
        externalId: 'demo-season',
        competitionExternalId: 'demo-league',
        name: SEASON,
        startDate: '2025-08-01',
        endDate: '2026-05-31',
      },
    ];
  }

  override async getTeams(): Promise<ProviderTeam[]> {
    return TEAM_NAMES.map((name, index) => ({
      externalId: `demo-team-${index}`,
      name,
      shortName: name.split(' ')[0] ?? name,
      country: 'Netherlands',
    }));
  }

  private squad(): DemoSquadPlayer[] {
    if (this.squadCache) return this.squadCache;

    const random = mulberry32(20260101);
    const players: DemoSquadPlayer[] = [];

    TEAM_NAMES.forEach((_, teamIndex) => {
      // Team strength shapes its players, so the league has a real table.
      const teamStrength = 0.35 + (TEAM_NAMES.length - teamIndex) / (TEAM_NAMES.length * 1.6);
      let squadIndex = 0;

      for (const slot of FORMATION) {
        for (let i = 0; i < slot.count; i += 1) {
          const externalId = `demo-player-${teamIndex}-${squadIndex}`;
          players.push({
            externalId,
            firstName: FIRST_NAMES[(teamIndex * 11 + squadIndex) % FIRST_NAMES.length] as string,
            lastName: LAST_NAMES[(teamIndex * 7 + squadIndex * 3) % LAST_NAMES.length] as string,
            position: slot.position,
            teamExternalId: `demo-team-${teamIndex}`,
            quality: Math.min(0.98, Math.max(0.15, teamStrength * (0.7 + random() * 0.6))),
          });
          squadIndex += 1;
        }
      }

      // Four substitutes per squad.
      for (let i = 0; i < 4; i += 1) {
        const externalId = `demo-player-${teamIndex}-${squadIndex}`;
        players.push({
          externalId,
          firstName: FIRST_NAMES[(teamIndex * 5 + squadIndex) % FIRST_NAMES.length] as string,
          lastName: LAST_NAMES[(teamIndex * 13 + squadIndex) % LAST_NAMES.length] as string,
          position: ['CB', 'CM', 'RW', 'ST'][i] as string,
          teamExternalId: `demo-team-${teamIndex}`,
          quality: Math.min(0.9, Math.max(0.12, teamStrength * (0.5 + random() * 0.5))),
        });
        squadIndex += 1;
      }
    });

    this.squadCache = players;
    return players;
  }

  override async getPlayers(): Promise<ProviderPlayer[]> {
    const random = mulberry32(7);

    return this.squad().map((player) => ({
      externalId: player.externalId,
      firstName: player.firstName,
      lastName: player.lastName,
      fullName: `${player.firstName} ${player.lastName}`,
      dateOfBirth: new Date(
        Date.UTC(1995 + Math.floor(random() * 12), Math.floor(random() * 12), 1 + Math.floor(random() * 27)),
      )
        .toISOString()
        .slice(0, 10),
      nationality: 'Netherlands',
      heightCm: 172 + Math.floor(random() * 22),
      preferredFoot: random() > 0.75 ? 'LEFT' : 'RIGHT',
      position: player.position,
      teamExternalId: player.teamExternalId,
    }));
  }

  /** Single round-robin, repeated until matchCount is reached. */
  private fixtures(): { home: number; away: number }[] {
    const fixtures: { home: number; away: number }[] = [];
    for (let home = 0; home < TEAM_NAMES.length; home += 1) {
      for (let away = 0; away < TEAM_NAMES.length; away += 1) {
        if (home !== away) fixtures.push({ home, away });
      }
    }
    return fixtures.slice(0, this.matchCount);
  }

  override async getMatches(params: MatchQuery = {}): Promise<ProviderMatch[]> {
    const random = mulberry32(99);

    return this.fixtures()
      .slice(0, params.limit ?? this.matchCount)
      .map((fixture, index) => {
        const kickoff = new Date(Date.UTC(2025, 7, 8 + index * 3, 18, 45));
        return {
          externalId: `demo-match-${index}`,
          competitionExternalId: 'demo-league',
          seasonExternalId: 'demo-season',
          homeTeamExternalId: `demo-team-${fixture.home}`,
          awayTeamExternalId: `demo-team-${fixture.away}`,
          kickoffAt: kickoff.toISOString(),
          homeScore: Math.floor(random() * 4),
          awayScore: Math.floor(random() * 3),
          matchweek: Math.floor(index / (TEAM_NAMES.length / 2)) + 1,
          venue: `${TEAM_NAMES[fixture.home]} Stadion`,
        };
      });
  }

  override async getLineups(matchExternalId: string): Promise<ProviderLineup[]> {
    const index = Number(matchExternalId.replace('demo-match-', ''));
    const fixture = this.fixtures()[index];
    if (!fixture) return [];

    return [fixture.home, fixture.away].map((teamIndex) => {
      const squad = this.squad().filter(
        (player) => player.teamExternalId === `demo-team-${teamIndex}`,
      );

      return {
        matchExternalId,
        teamExternalId: `demo-team-${teamIndex}`,
        formation: '4-3-3',
        players: squad.map((player, squadIndex) => ({
          playerExternalId: player.externalId,
          teamExternalId: `demo-team-${teamIndex}`,
          position: player.position,
          shirtNumber: squadIndex + 1,
          isStarter: squadIndex < 11,
          minutesPlayed: squadIndex < 11 ? 90 : squadIndex < 14 ? 20 : 0,
        })),
      };
    });
  }

  /**
   * Generate a match's events.
   *
   * Not a simulation of football, but shaped enough that the analytics have
   * something meaningful to chew on: better players get more of the ball,
   * forwards shoot from dangerous areas, defenders defend deep, and
   * coordinates land where those actions actually happen.
   */
  override async getEvents(matchExternalId: string): Promise<ProviderEvent[]> {
    const index = Number(matchExternalId.replace('demo-match-', ''));
    const fixture = this.fixtures()[index];
    if (!fixture) return [];

    const random = mulberry32(1000 + index);
    const events: ProviderEvent[] = [];
    let sequence = 0;

    const lineup = [fixture.home, fixture.away].flatMap((teamIndex) =>
      this.squad()
        .filter((player) => player.teamExternalId === `demo-team-${teamIndex}`)
        .slice(0, 11)
        .map((player) => ({ ...player, teamIndex })),
    );

    const EVENTS_PER_MATCH = 900;

    for (let i = 0; i < EVENTS_PER_MATCH; i += 1) {
      const minute = Math.min(94, Math.floor((i / EVENTS_PER_MATCH) * 94));
      const period = minute < 45 ? 1 : 2;
      const actor = lineup[Math.floor(random() * lineup.length)];
      if (!actor) continue;

      const attackingHome = actor.teamIndex === fixture.home;
      const group = positionGroupOf(actor.position);

      // Where on the pitch this player tends to act.
      const base =
        group === 'GK' ? 0.06 : group === 'DF' ? 0.3 : group === 'MF' ? 0.52 : 0.74;
      const x = clamp((base + (random() - 0.5) * 0.3) * PITCH_LENGTH_M, 1, PITCH_LENGTH_M - 1);
      const y = clamp(random() * PITCH_WIDTH_M, 1, PITCH_WIDTH_M - 1);

      const roll = random();
      const teamExternalId = `demo-team-${actor.teamIndex}`;
      const opponentIndex = actor.teamIndex === fixture.home ? fixture.away : fixture.home;
      // A defensive action happens while the OTHER team has the ball. Making
      // the possession team always the acting team would leave the possession
      // filters of §38 unable to tell anything apart.
      const inPossession = roll >= 0.2 || group === 'FW';
      const common = {
        matchExternalId,
        teamExternalId,
        playerExternalId: actor.externalId,
        possessionTeamExternalId: inPossession
          ? teamExternalId
          : `demo-team-${opponentIndex}`,
        minute,
        second: Math.floor(random() * 60),
        period,
        timestampMs: minute * 60_000,
        underPressure: random() < 0.22,
        // Most of the ball is in open play; the rest restarts from a dead ball.
        // Without this the open-play filter of §38 has nothing to separate.
        playPattern: inPossession ? DEMO_PLAY_PATTERNS[Math.floor(random() * DEMO_PLAY_PATTERNS.length)] ?? 'Regular Play' : 'Regular Play',
      };

      // Shots: forwards and attacking midfielders, from the final third.
      if (roll < 0.045 && group !== 'GK' && x > PITCH_LENGTH_M * 0.6) {
        const shotX = clamp(PITCH_LENGTH_M - random() * 28, 70, PITCH_LENGTH_M - 2);
        const shotY = clamp(PITCH_WIDTH_M / 2 + (random() - 0.5) * 26, 4, PITCH_WIDTH_M - 4);
        const quality = actor.quality;
        const xg = clamp(0.04 + quality * 0.22 * random() * 2, 0.01, 0.85);
        const isGoal = random() < xg * (0.6 + quality * 0.5);

        events.push({
          ...common,
          externalId: `${matchExternalId}-${sequence++}`,
          type: 'SHOT',
          x: shotX,
          y: shotY,
          outcome: isGoal ? 'Goal' : random() < 0.35 ? 'Saved' : 'Off T',
          detail: {
            shot: {
              xg: Math.round(xg * 1000) / 1000,
              providerXg: null,
              bodyPart: random() < 0.15 ? 'HEAD' : 'RIGHT_FOOT',
              isGoal,
              onTarget: isGoal || random() < 0.45,
              blocked: !isGoal && random() < 0.15,
              isPenalty: false,
              isSetPiece: random() < 0.12,
            },
          },
        });
        continue;
      }

      // Defensive actions: deeper players, own half.
      if (roll < 0.2 && group !== 'FW') {
        const kind = random();
        const type =
          kind < 0.3 ? 'TACKLE' : kind < 0.55 ? 'INTERCEPTION' : kind < 0.8 ? 'RECOVERY' : 'CLEARANCE';

        events.push({
          ...common,
          externalId: `${matchExternalId}-${sequence++}`,
          type,
          x: clamp(x * 0.7, 1, PITCH_LENGTH_M - 1),
          y,
          outcome: null,
          detail: {
            tackle: type === 'TACKLE' ? { won: random() < 0.45 + actor.quality * 0.3 } : undefined,
            recovery: type === 'RECOVERY' ? { failed: random() < 0.15 } : undefined,
            clearance: type === 'CLEARANCE' ? { bodyPart: 'RIGHT_FOOT' } : undefined,
          },
        });
        continue;
      }

      // Pressures.
      if (roll < 0.3) {
        events.push({
          ...common,
          externalId: `${matchExternalId}-${sequence++}`,
          type: 'PRESSURE',
          x,
          y,
          outcome: null,
          detail: { pressure: { durationSec: Math.round(random() * 3 * 10) / 10, counterpress: random() < 0.3 } },
        });
        continue;
      }

      // Duels.
      if (roll < 0.36) {
        events.push({
          ...common,
          externalId: `${matchExternalId}-${sequence++}`,
          type: 'DUEL',
          x,
          y,
          outcome: null,
          detail: {
            duel: {
              duelType: random() < 0.4 ? 'AERIAL' : 'GROUND',
              won: random() < 0.35 + actor.quality * 0.4,
            },
          },
        });
        continue;
      }

      // Carries and dribbles.
      if (roll < 0.48) {
        const endX = clamp(x + random() * 18 - 3, 1, PITCH_LENGTH_M - 1);
        const endY = clamp(y + (random() - 0.5) * 16, 1, PITCH_WIDTH_M - 1);

        events.push({
          ...common,
          externalId: `${matchExternalId}-${sequence++}`,
          type: random() < 0.25 ? 'DRIBBLE' : 'CARRY',
          x,
          y,
          endX,
          endY,
          outcome: random() < 0.45 + actor.quality * 0.4 ? 'COMPLETE' : 'INCOMPLETE',
          detail: {
            dribble: { completed: random() < 0.4 + actor.quality * 0.4 },
          },
        });
        continue;
      }

      // Everything else is a pass.
      const forward = random() < 0.45 + actor.quality * 0.25;
      const endX = clamp(forward ? x + random() * 30 : x - random() * 15, 1, PITCH_LENGTH_M - 1);
      const endY = clamp(y + (random() - 0.5) * 30, 1, PITCH_WIDTH_M - 1);
      const completed = random() < 0.62 + actor.quality * 0.3;
      // A completed pass reached someone. Without a recipient the passing
      // network of §38 has nodes but no edges, so the demo league would show
      // an empty picture where real data shows a team shape.
      const recipient = completed ? pickRecipient(lineup, actor, endX, random) : null;
      const keyPass = completed && endX > PITCH_LENGTH_M * 0.8 && random() < 0.06;

      events.push({
        ...common,
        externalId: `${matchExternalId}-${sequence++}`,
        type: 'PASS',
        x,
        y,
        endX,
        endY,
        outcome: completed ? null : 'Incomplete',
        detail: {
          pass: {
            recipientExternalId: recipient,
            lengthM: Math.round(Math.hypot(endX - x, endY - y) * 10) / 10,
            angleRad: Math.atan2(endY - y, endX - x),
            height: random() < 0.75 ? 'GROUND' : 'HIGH',
            bodyPart: 'RIGHT_FOOT',
            completed,
            isCross: endX > PITCH_LENGTH_M * 0.8 && (y < 14 || y > PITCH_WIDTH_M - 14),
            isSwitch: Math.abs(endY - y) > 30,
            isThroughBall: random() < 0.03,
            isCutback: false,
            isKeyPass: keyPass,
            isAssist: keyPass && random() < 0.25,
          },
        },
      });
    }

    return events;
  }
}

/**
 * Play patterns the demo league uses, weighted towards open play by repetition.
 * Named as StatsBomb names them so the demo exercises the same code paths as
 * real data does.
 */
const DEMO_PLAY_PATTERNS = [
  'Regular Play',
  'Regular Play',
  'Regular Play',
  'Regular Play',
  'Regular Play',
  'Regular Play',
  'From Counter',
  'From Throw In',
  'From Free Kick',
  'From Corner',
  'From Goal Kick',
] as const;

const clamp = (value: number, min: number, max: number): number =>
  Math.min(max, Math.max(min, value));

/** Where a position typically operates along the pitch, in metres. */
const zoneX = (position: string): number => {
  const group = positionGroupOf(position);
  const base = group === 'GK' ? 0.06 : group === 'DF' ? 0.3 : group === 'MF' ? 0.52 : 0.74;
  return base * PITCH_LENGTH_M;
};

/**
 * Choose who received a completed pass.
 *
 * The nearest team-mate by typical zone, chosen from the closest few so the
 * network has some spread rather than one deterministic edge per pair. This is
 * plausible shape, not a simulation - as with everything else the demo provider
 * produces, and the reason its output is labelled DEMO DATA throughout.
 */
function pickRecipient(
  lineup: { externalId: string; position: string; teamIndex: number }[],
  actor: { externalId: string; teamIndex: number },
  endX: number,
  random: () => number,
): string | null {
  const candidates = lineup
    .filter((mate) => mate.teamIndex === actor.teamIndex && mate.externalId !== actor.externalId)
    .map((mate) => ({ mate, distance: Math.abs(zoneX(mate.position) - endX) }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, 3);

  return candidates[Math.floor(random() * candidates.length)]?.mate.externalId ?? null;
}

function positionGroupOf(position: string): 'GK' | 'DF' | 'MF' | 'FW' {
  if (position === 'GK') return 'GK';
  if (['CB', 'LB', 'RB', 'LWB', 'RWB'].includes(position)) return 'DF';
  if (['CDM', 'CM', 'CAM', 'LM', 'RM'].includes(position)) return 'MF';
  return 'FW';
}

export const DEMO_DATA_LABEL = DEMO_LABEL;
